export const product = [
  {
    id: 1,
    img: "/men-style-1.jpg",
    title: "Shirt",
    desc: "Red and Black Checkered Shirt",
    features: ["100% Cotton", "Slim Fit", "Machine Washable"],
    rating: 4,
    reviews: 6,
    price: "3000",
  },
  {
    id: 2,
    img: "/men-style-2.jpg",
    title: "Coat",
    desc: "Blue Denim Coat",
    features: ["Cotton Thread", "Twill Weave", "Durable", "Regular Fit"],
    rating: 5,
    reviews: 4,
    price: "9000",
  },
  {
    id: 3,
    img: "/men-style-3.jpg",
    title: "Sleeves",
    desc: "Blue Linen Long Sleeves",
    features: [
      "100% Linen",
      "Lint Free",
      "Strong Fabric",
      "Any Size Available",
    ],
    rating: 4.5,
    reviews: 7,
    price: "3500",
  },
  {
    id: 4,
    img: "/men-style-4.jpg",
    title: "Sleeves",
    desc: "White and Black Striped Long Sleeves",
    features: [
      "100% Cotton",
      "Slim Fit",
      "Machine Washable",
      "Any Size Available",
    ],
    rating: 4.5,
    reviews: 3,
    price: "5000",
  },
  {
    id: 5,
    img: "/women-style-1.jpg",
    title: "Blazer",
    desc: "Red Women's Blazer",
    features: ["Tailored Fit", "Dry Clean Only", "Any Size Available", "Lined"],
    rating: 4,
    reviews: 5,
    price: "6000",
  },
  {
    id: 6,
    img: "/women-style-2.jpg",
    title: "Skinny",
    desc: "White Skinny",
    features: [
      "100% Cotton",
      "Slim Fit",
      "Machine Washable",
      "Any Size Available",
    ],
    rating: 3.5,
    reviews: 4,
    price: "2500",
  },
  {
    id: 7,
    img: "/women-style-3.jpg",
    title: "Blazer",
    desc: "Pink Women's Blazer",
    features: ["Tailored Fit", "Dry Clean Only", "Any Size Available", "Lined"],
    rating: 5,
    reviews: 8,
    price: "8000",
  },
  {
    id: 8,
    img: "/women-style-4.jpg",
    title: "Coat",
    desc: "Wool Coat",
    features: ["High Quality Wool", "Well Stitched", "Durable", "Fit"],
    rating: 5,
    reviews: 6,
    price: "10000",
  },
];
